version: '3.8'

services:
  apiforgovermentapp:
    build:
      context: .
      dockerfile: ApiForGovermentApp/Dockerfile
    ports:
      - "5138:5138"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Database=ApiDb;User ID=sa;Password=Your_password123;TrustServerCertificate=True;"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  sqlserverdata:
