version: '3.8'

services:
  apiforgovermentapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - /c/Users/kosyk/AppData/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /c/Users/kosyk/AppData/Roaming/ASP.NET/Https:/root/.aspnet/https:ro
