version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      SA_PASSWORD: StrongPassword1231
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - /db:/var/opt/mssql
    networks:
      - app-network

  webapp:
    build: ./aspnetapp
    container_name: aspnet_webapp
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql_db;Database=Products;User Id=sa;Password=StrongPassword1231;"
    ports:
      - "5000:80"  
    depends_on:
      - mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
